### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by fpg1503** [barbosa/clorox#17]
Whenever I try to run clorox I get the following error:

```
$ clorox --path ProjectX
Traceback (most recent call last):
  File "/usr/local/bin/clorox", line 9, in <module>
    load_entry_point('clorox==0.5', 'console_scripts', 'clorox')()
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/setuptools-9.1-py3.4.egg/pkg_resources/__init__.py", line 474, in load_entry_point
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/setuptools-9.1-py3.4.egg/pkg_resources/__init__.py", line 2569, in load_entry_point
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/setuptools-9.1-py3.4.egg/pkg_resources/__init__.py", line 2260, in load
  File "/usr/local/lib/python3.4/site-packages/clorox/clorox.py", line 88
    print 'You must provide a directory to be cleaned using the --dir option'
                                                                            ^
SyntaxError: Missing parentheses in call to 'print'
```

**Environment**
- macOS 10.12
- Python 3.4.2 installed via hombebrew
- pip 7.1.2 from /usr/local/lib/python3.4/site-packages (python 3.4)
- clorox-0.5 
- couleur-0.6.2

**Reproducible**
- Always

Am I doing something wrong?

**Comment by fpg1503** [comment]
Never mind, I just realized I should be using Python 2.7, installing using `pip2.7` did the trick.
